#!/bin/bash
# collect-and-report.sh — run on report.timer, pull data and generate markdown
set -euo pipefail
cd "$HOME/code/field-monitor"

# Pull latest data from all servers
./scripts/collect.sh

# Report already generated by collect.sh
echo "Report updated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"

# Retain last 7 days of archived reports
RESULTS_DIR="${RESULTS_DIR:-$HOME/.local/share/field-monitor}"
find "$RESULTS_DIR" -name "report-*" -mtime +7 -delete 2>/dev/null || true