#!/bin/bash
# collect-and-report.sh — run on report.timer, pull data from servers and generate markdown
set -euo pipefail
cd $HOME/code/field-monitor

# Pull latest data from all servers
./scripts/collect.sh

# Report already generated by collect.sh
echo "Report updated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"