//! Data types and parsing for targets and servers.
//!
//! IMPORTANT: the code knows NO concrete domain or host. The target
//! allowlist is defined by the operator in a PRIVATE file (`targets.toml`,
//! git-ignored) and loaded into `Config.targets`. `is_safe()` only confirms
//! that a target came from config (not generated by the agent on the fly).

use serde::{Deserialize, Serialize};

/// A measurement target. The agent refuses to measure anything not in the allowlist.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Target {
    /// Display name of the target.
    pub name: String,
    /// DNS name for resolution and HTTPS (empty for raw IP/ICMP).
    pub host: String,
    /// URL for the HTTPS check (empty = do not measure HTTPS).
    pub url: String,
    /// Explicit IP (for ICMP / raw TCP, bypassing resolution).
    pub ip: String,
}

impl Target {
    /// Sanitize a target: reject suspicious patterns (hidden ports, paths to
    /// third-party admin panels, shell metacharacters, injection attempts).
    /// The allowlist itself bounds the set, but as a safeguard we also do a
    /// basic character check so a misconfigured/malicious `targets.toml`
    /// cannot smuggle an injection through host/url/ip.
    pub fn is_safe(&self) -> bool {
        // `name` is written into CSV/AUDIT emit lines (`target,{name},...`) and
        // parsed downstream, so it must not contain the field/line delimiters
        // (`,` `|` newlines) or control chars that would corrupt the report.
        let name_ok = !self.name.is_empty()
            && !self.name.contains(',')
            && !self.name.contains('|')
            && !self.name.chars().any(|c| c.is_control());
        let host_ok = self.host.is_empty()
            || (no_injection_chars(&self.host)
                && !self.host.contains(':')
                && !self.host.contains('/'));
        let url_ok = self.url.is_empty()
            || (self.url.starts_with("http://") || self.url.starts_with("https://"))
                && no_injection_chars(&self.url);
        let ip_ok = self.ip.is_empty() || valid_ip(&self.ip);
        name_ok && host_ok && url_ok && ip_ok
    }
}

/// Reject shell metacharacters / whitespace / control chars that could be
/// used to break out of a command or a quoted argument.
fn no_injection_chars(s: &str) -> bool {
    !s.contains('\'')
        && !s.contains('"')
        && !s.contains('$')
        && !s.contains(';')
        && !s.contains('|')
        && !s.contains('&')
        && !s.contains('`')
        && !s.contains('\\')
        && !s.chars().any(|c| c.is_whitespace() || c.is_control())
}

/// Validate an IP: empty, IPv4 (4 octets 0-255), or IPv6 (heuristic: contains
/// ':' and only hex digits / ':' / '.').
fn valid_ip(s: &str) -> bool {
    if s.is_empty() {
        return true;
    }
    let octets: Vec<&str> = s.split('.').collect();
    if octets.len() == 4 && octets.iter().all(|o| o.parse::<u8>().is_ok()) {
        return true;
    }
    // IPv6 heuristic
    s.contains(':')
        && s.chars()
            .all(|c| c.is_ascii_hexdigit() || c == ':' || c == '.')
}

/// Default targets — EMPTY. The operator MUST define them in the private
/// `targets.toml` (git-ignored). The code ships no hardcoded hosts.
pub fn default_targets() -> Vec<Target> {
    vec![]
}

/// Configuration loaded from `config.toml` + `targets.toml`. Servers are also listed explicitly.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Config {
    /// Servers to run probes on (orchestrator).
    pub servers: Vec<ServerEntry>,
    /// Measurement targets (allowlist). MUST be set by the operator
    /// (private targets.toml). An empty list means nothing to measure.
    pub targets: Vec<Target>,
    /// Minimum interval between measurements of one target, in seconds (rate-limit).
    #[serde(default = "default_interval")]
    pub min_interval_sec: u64,
    /// Max number of servers probed in parallel per batch (0 = unlimited).
    #[serde(default = "default_batch")]
    pub batch_size: usize,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ServerEntry {
    /// Public IP of the host.
    pub ip: String,
    /// Label used in logs.
    pub name: String,
    /// SSH private key path (on the operator's machine).
    pub key: String,
    /// SSH port.
    #[serde(default = "default_port")]
    pub port: u16,
    /// SSH user on the host (required — the username on the server, not a default operator).
    pub user: String,
    /// Architecture of the binary on the server. Affects which locally built
    /// binary is copied over (cross-build). `"x86_64"` (default) | `"aarch64"`.
    #[serde(default = "default_arch")]
    pub arch: String,
}

fn default_arch() -> String {
    "x86_64".into()
}

fn default_port() -> u16 {
    22
}
fn default_interval() -> u64 {
    300
}

fn default_batch() -> usize {
    4
}

/// ISO8601 timestamp without external crates. Used for reports and logs.
pub fn timestamp_iso8601(secs: u64) -> String {
    let days = secs / 86400;
    let mut year = 1970;
    let mut d = days;
    let month_days = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31];
    while d >= 365 {
        let leap = if (year % 4 == 0 && year % 100 != 0) || (year % 400 == 0) {
            366
        } else {
            365
        };
        if d >= leap {
            d -= leap;
            year += 1;
        } else {
            break;
        }
    }
    let mut month = 0;
    while month < 12 && d >= month_days[month] {
        d -= month_days[month];
        month += 1;
    }
    let day = d + 1;
    let mon = month + 1;
    let rem = secs % 86400;
    let hour = rem / 3600;
    let min = (rem % 3600) / 60;
    let sec = rem % 60;
    format!(
        "{:02}-{:02}-{:02}T{:02}:{:02}:{:02}Z",
        year, mon, day, hour, min, sec
    )
}

impl Default for Config {
    fn default() -> Self {
        Config {
            servers: vec![],
            targets: default_targets(),
            min_interval_sec: 300,
            batch_size: 4,
        }
    }
}

/// A single measurement row.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProbeRow {
    /// Server IP.
    pub server: String,
    /// Server label.
    pub label: String,
    /// Target name.
    pub target: String,
    /// Resolved DNS IP.
    pub dns_ip: String,
    /// DNS resolution time (ms).
    pub dns_ms: Option<u64>,
    /// HTTPS status code.
    pub https_code: Option<u16>,
    /// HTTPS response time (ms).
    pub https_ms: Option<u64>,
    /// TCP connect result (e.g. "open").
    pub tcp: String,
    /// TCP connect time (ms).
    pub tcp_ms: Option<u64>,
    /// ICMP result (e.g. "ok").
    pub icmp: String,
    /// ICMP round-trip time (ms).
    pub icmp_ms: Option<u64>,
    /// false = broken metric (timer overflow, etc.), excluded from statistics.
    pub sane: bool,
    /// true = at least one sub-check (DNS/HTTPS/TCP/ICMP) failed to run, so the
    /// row is a partial result, not a definitive "target is dead" verdict.
    pub partial: bool,
}

/// A security-audit row.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AuditRow {
    /// Host IP.
    pub ip: String,
    /// Host label.
    pub name: String,
    /// sudo NOPASSWD status.
    pub sudo_nopass: String,
    /// OS description.
    pub os: String,
    /// SSH port.
    pub ssh_port: String,
    /// SSH password auth status.
    pub ssh_pw: String,
    /// PermitRootLogin status.
    pub ssh_root: String,
    /// ufw status.
    pub ufw: String,
    /// fail2ban status.
    pub fail2ban: String,
    /// docker status.
    pub docker: String,
    /// Listening ports.
    pub ports: String,
}

/// Aggregated summary.
#[derive(Debug, Serialize, Deserialize)]
pub struct Summary {
    /// Number of vantage points.
    pub n_points: usize,
    /// Per-server info.
    pub servers: Vec<ServerInfo>,
    /// Probe rows.
    pub rows: Vec<ProbeRow>,
    /// Detected anomalies.
    pub anomalies: Vec<Anomaly>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct ServerInfo {
    /// Server IP.
    pub ip: String,
    /// Server label.
    pub label: String,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct Anomaly {
    /// Server IP.
    pub ip: String,
    /// Server label.
    pub label: String,
    /// Target name.
    pub target: String,
    /// HTTPS status code (if any).
    pub https_code: Option<u16>,
    /// HTTPS response time (ms, if any).
    pub https_ms: Option<u64>,
    /// TCP result.
    pub tcp: String,
}

/// Select the locally-built binary for a server of the given architecture.
///
/// For `arch == "aarch64"` returns the cross-compiled binary at
/// `<repo>/target/aarch64-unknown-linux-gnu/release/field-monitor`.
/// For everything else (default x86_64) returns the executable itself
/// (`self_exe`), i.e. the binary for the current architecture.
///
/// Pure function (takes `self_exe` explicitly) — easy to test.
pub fn bin_for_arch(arch: &str, self_exe: &std::path::Path) -> std::path::PathBuf {
    if arch.trim() == "aarch64" {
        let mut p = self_exe
            .parent()
            .map(|p| p.to_path_buf())
            .unwrap_or_default();
        // self_exe = .../target/<host-triple>/release/field-monitor
        // parent() = .../target/<host-triple>/release
        p.pop(); // release
        p.pop(); // <host-triple> (e.g. x86_64-unknown-linux-gnu)
        p.push("target");
        p.push("aarch64-unknown-linux-gnu");
        p.push("release");
        p.push("field-monitor");
        p
    } else {
        self_exe.to_path_buf()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::Path;

    #[test]
    fn allowlist_only_known_targets() {
        // is_safe() now only sanitizes (no hardcoded hosts):
        // any operator-defined target passes; injection-like host/url fails.
        let good = Target {
            name: "example".into(),
            host: "example.com".into(),
            url: "https://example.com".into(),
            ip: "".into(),
        };
        assert!(good.is_safe());
        // bad: host with a port or path (injection attempt)
        let bad = Target {
            name: "evil".into(),
            host: "evil.com:443".into(),
            url: "https://evil.com".into(),
            ip: "".into(),
        };
        assert!(!bad.is_safe());
    }

    #[test]
    fn ip_only_target_is_safe() {
        // an IP-only target (no host/url) is a legitimate ICMP target.
        // Use an RFC5737 TEST-NET-3 address as a placeholder (never a real IP).
        let t = Target {
            name: "dns-resolver".into(),
            host: "".into(),
            url: "".into(),
            ip: "203.0.113.5".into(),
        };
        assert!(t.is_safe());
    }

    #[test]
    fn is_safe_rejects_injection_in_host() {
        // A single quote in host must be rejected (would break a quoted arg).
        let t = Target {
            name: "evil".into(),
            host: "example.com'".into(),
            url: "".into(),
            ip: "".into(),
        };
        assert!(!t.is_safe());
    }

    #[test]
    fn is_safe_rejects_bad_ip() {
        // A non-IP string in the ip field must be rejected.
        let t = Target {
            name: "evil".into(),
            host: "".into(),
            url: "".into(),
            ip: "not an ip; rm -rf /".into(),
        };
        assert!(!t.is_safe());
    }

    #[test]
    fn is_safe_accepts_valid_ipv4_and_ipv6() {
        assert!(Target {
            name: "a".into(),
            host: "".into(),
            url: "".into(),
            ip: "192.0.2.10".into()
        }
        .is_safe());
        assert!(Target {
            name: "a".into(),
            host: "".into(),
            url: "".into(),
            ip: "2001:db8::1".into()
        }
        .is_safe());
    }

    #[test]
    fn is_safe_rejects_injection_in_name() {
        // name is written into CSV/AUDIT emit lines, so delimiters/control
        // chars must be rejected (closes cycle-5 ARCH-1).
        assert!(!Target {
            name: "a,b".into(),
            host: "".into(),
            url: "".into(),
            ip: "".into()
        }
        .is_safe());
        assert!(!Target {
            name: "x|y".into(),
            host: "".into(),
            url: "".into(),
            ip: "".into()
        }
        .is_safe());
        assert!(!Target {
            name: "x\ny".into(),
            host: "".into(),
            url: "".into(),
            ip: "".into()
        }
        .is_safe());
        assert!(!Target {
            name: "".into(),
            host: "".into(),
            url: "".into(),
            ip: "".into()
        }
        .is_safe());
        // a plain name is fine
        assert!(Target {
            name: "GitHub".into(),
            host: "".into(),
            url: "".into(),
            ip: "".into()
        }
        .is_safe());
    }

    #[test]
    fn bin_for_arch_x86_64_returns_self() {
        let exe = Path::new("/home/operator/code/field-monitor/target/release/field-monitor");
        let got = bin_for_arch("x86_64", exe);
        assert_eq!(got, exe);
        // default (empty string) is also x86_64
        assert_eq!(bin_for_arch("", exe), exe);
    }

    #[test]
    fn bin_for_arch_aarch64_points_to_target_triple() {
        let exe = Path::new("/home/operator/code/field-monitor/target/release/field-monitor");
        let got = bin_for_arch("aarch64", exe);
        assert_eq!(
            got,
            Path::new("/home/operator/code/field-monitor/target/aarch64-unknown-linux-gnu/release/field-monitor")
        );
    }

    #[test]
    fn timestamp_iso8601_format() {
        // Test that timestamp function produces expected format
        let ts = timestamp_iso8601(1735048000); // 2024-12-25
        assert!(ts.contains('T'));
        assert!(ts.ends_with('Z'));
    }
}
