//! Data types and parsing for targets and servers.
//!
//! IMPORTANT: the code knows NO concrete domain or host. The target
//! allowlist is defined by the operator in a PRIVATE file (`targets.toml`,
//! git-ignored) and loaded into `Config.targets`. `is_safe()` only confirms
//! that a target came from config (not generated by the agent on the fly).

use serde::{Deserialize, Serialize};

/// A measurement target. The agent refuses to measure anything not in the allowlist.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Target {
    /// Display name of the target.
    pub name: String,
    /// DNS name for resolution and HTTPS (empty for raw IP/ICMP).
    pub host: String,
    /// URL for the HTTPS check (empty = do not measure HTTPS).
    pub url: String,
    /// Explicit IP (for ICMP / raw TCP, bypassing resolution).
    pub ip: String,
}

impl Target {
    /// Sanitize a target: reject suspicious patterns (hidden ports, paths to
    /// third-party admin panels, etc.). The allowlist itself bounds the set,
    /// but as a safeguard we also do a basic character check.
    pub fn is_safe(&self) -> bool {
        // A target is safe if it parsed from config (i.e. explicitly listed by
        // the operator in the private targets.toml). Extra sanitization: no
        // unexpected characters in host/url.
        let host_ok = self.host.is_empty() || !self.host.contains(':') && !self.host.contains('/');
        let url_ok = self.url.is_empty()
            || self.url.starts_with("http://")
            || self.url.starts_with("https://");
        host_ok && url_ok
    }
}

/// Default targets — EMPTY. The operator MUST define them in the private
/// `targets.toml` (git-ignored). The code ships no hardcoded hosts.
pub fn default_targets() -> Vec<Target> {
    vec![]
}

/// Configuration loaded from `config.toml` + `targets.toml`. Servers are also listed explicitly.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Config {
    /// Servers to run probes on (orchestrator).
    pub servers: Vec<ServerEntry>,
    /// Measurement targets (allowlist). MUST be set by the operator
    /// (private targets.toml). An empty list means nothing to measure.
    pub targets: Vec<Target>,
    /// Minimum interval between measurements of one target, in seconds (rate-limit).
    #[serde(default = "default_interval")]
    pub min_interval_sec: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ServerEntry {
    /// Public IP of the host.
    pub ip: String,
    /// Label used in logs.
    pub name: String,
    /// SSH private key path (on the operator's machine).
    pub key: String,
    /// SSH port.
    #[serde(default = "default_port")]
    pub port: u16,
    /// SSH user on the host (required — the username on the server, not a default operator).
    pub user: String,
    /// Architecture of the binary on the server. Affects which locally built
    /// binary is copied over (cross-build). `"x86_64"` (default) | `"aarch64"`.
    #[serde(default = "default_arch")]
    pub arch: String,
}

fn default_arch() -> String {
    "x86_64".into()
}

fn default_port() -> u16 {
    22
}
fn default_interval() -> u64 {
    300
}

impl Default for Config {
    fn default() -> Self {
        Config {
            servers: vec![],
            targets: default_targets(),
            min_interval_sec: 300,
        }
    }
}

/// A single measurement row.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProbeRow {
    /// Server IP.
    pub server: String,
    /// Server label.
    pub label: String,
    /// Target name.
    pub target: String,
    /// Resolved DNS IP.
    pub dns_ip: String,
    /// DNS resolution time (ms).
    pub dns_ms: Option<u64>,
    /// HTTPS status code.
    pub https_code: Option<u16>,
    /// HTTPS response time (ms).
    pub https_ms: Option<u64>,
    /// TCP connect result (e.g. "open").
    pub tcp: String,
    /// TCP connect time (ms).
    pub tcp_ms: Option<u64>,
    /// ICMP result (e.g. "ok").
    pub icmp: String,
    /// ICMP round-trip time (ms).
    pub icmp_ms: Option<u64>,
    /// false = broken metric (timer overflow, etc.), excluded from statistics.
    pub sane: bool,
}

/// A security-audit row.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AuditRow {
    /// Host IP.
    pub ip: String,
    /// Host label.
    pub name: String,
    /// sudo NOPASSWD status.
    pub sudo_nopass: String,
    /// OS description.
    pub os: String,
    /// SSH port.
    pub ssh_port: String,
    /// SSH password auth status.
    pub ssh_pw: String,
    /// PermitRootLogin status.
    pub ssh_root: String,
    /// ufw status.
    pub ufw: String,
    /// fail2ban status.
    pub fail2ban: String,
    /// docker status.
    pub docker: String,
    /// Listening ports.
    pub ports: String,
}

/// Aggregated summary.
#[derive(Debug, Serialize, Deserialize)]
pub struct Summary {
    /// Number of vantage points.
    pub n_points: usize,
    /// Per-server info.
    pub servers: Vec<ServerInfo>,
    /// Probe rows.
    pub rows: Vec<ProbeRow>,
    /// Detected anomalies.
    pub anomalies: Vec<Anomaly>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct ServerInfo {
    /// Server IP.
    pub ip: String,
    /// Server label.
    pub label: String,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct Anomaly {
    /// Server IP.
    pub ip: String,
    /// Server label.
    pub label: String,
    /// Target name.
    pub target: String,
    /// HTTPS status code (if any).
    pub https_code: Option<u16>,
    /// HTTPS response time (ms, if any).
    pub https_ms: Option<u64>,
    /// TCP result.
    pub tcp: String,
}

/// Select the locally-built binary for a server of the given architecture.
///
/// For `arch == "aarch64"` returns the cross-compiled binary at
/// `<repo>/target/aarch64-unknown-linux-gnu/release/field-monitor`.
/// For everything else (default x86_64) returns the executable itself
/// (`self_exe`), i.e. the binary for the current architecture.
///
/// Pure function (takes `self_exe` explicitly) — easy to test.
pub fn bin_for_arch(arch: &str, self_exe: &std::path::Path) -> std::path::PathBuf {
    if arch.trim() == "aarch64" {
        let mut p = self_exe
            .parent()
            .map(|p| p.to_path_buf())
            .unwrap_or_default();
        // self_exe = .../target/<host-triple>/release/field-monitor
        // parent() = .../target/<host-triple>/release
        p.pop(); // release
        p.pop(); // <host-triple> (e.g. x86_64-unknown-linux-gnu)
        p.push("target");
        p.push("aarch64-unknown-linux-gnu");
        p.push("release");
        p.push("field-monitor");
        p
    } else {
        self_exe.to_path_buf()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::Path;

    #[test]
    fn allowlist_only_known_targets() {
        // is_safe() now only sanitizes (no hardcoded hosts):
        // any operator-defined target passes; injection-like host/url fails.
        let good = Target {
            name: "example".into(),
            host: "example.com".into(),
            url: "https://example.com".into(),
            ip: "".into(),
        };
        assert!(good.is_safe());
        // bad: host with a port or path (injection attempt)
        let bad = Target {
            name: "evil".into(),
            host: "evil.com:443".into(),
            url: "https://evil.com".into(),
            ip: "".into(),
        };
        assert!(!bad.is_safe());
    }

    #[test]
    fn ip_only_target_is_safe() {
        // an IP-only target (no host/url) is a legitimate ICMP target.
        let t = Target {
            name: "dns-resolver".into(),
            host: "".into(),
            url: "".into(),
            ip: "YOUR_DNS_IP".into(),
        };
        assert!(t.is_safe());
    }

    #[test]
    fn bin_for_arch_x86_64_returns_self() {
        let exe = Path::new("/home/operator/code/field-monitor/target/release/field-monitor");
        let got = bin_for_arch("x86_64", exe);
        assert_eq!(got, exe);
        // default (empty string) is also x86_64
        assert_eq!(bin_for_arch("", exe), exe);
    }

    #[test]
    fn bin_for_arch_aarch64_points_to_target_triple() {
        let exe = Path::new("/home/operator/code/field-monitor/target/release/field-monitor");
        let got = bin_for_arch("aarch64", exe);
        assert_eq!(
            got,
            Path::new("/home/operator/code/field-monitor/target/aarch64-unknown-linux-gnu/release/field-monitor")
        );
    }
}
